# Production Profile - Railway deployment
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# OpenAI
openai.api.key=${OPENAI_API_KEY}

# Supabase JWT
supabase.jwt.secret=${SUPABASE_JWT_SECRET}

# Logging - No need to debug in production
logging.level.com.prepai=INFO
logging.level.org.hibernate.SQL=WARN

# Swagger - we will diable it in production (optional)
springdoc.swagger-ui.enabled=true